version: "3.8"

services:
  mysql:
    container_name: ${CONTAINER_NAME}
    networks:
      - mysql
    restart: unless-stopped
    image: mysql
    working_dir: /etc/shared
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PORT}:3306"
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - mysql
    container_name: ${CONTAINER_NAME}-pma
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${CONTAINER_NAME}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}


volumes:
  data:

networks:
  mysql:
    driver: bridge
    name: mysql